# Generated by Django 2.2.5 on 2019-09-30 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('postcode', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=200)),
                ('detailAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('extraAddress', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_reg_no', models.CharField(max_length=50, unique=True)),
                ('enterprise_name', models.CharField(max_length=50)),
                ('industry_code', models.CharField(max_length=50)),
                ('enterprise_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodName', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=20)),
                ('orderUnit', models.CharField(max_length=20)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersystem.Enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('postcode', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=200)),
                ('detailAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('extraAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('customid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDay', models.DateTimeField()),
                ('endDay', models.DateTimeField()),
                ('salePrice', models.IntegerField()),
                ('saleUnit', models.CharField(max_length=20)),
                ('goodNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersystem.Goods')),
            ],
            options={
                'unique_together': {('goodNo', 'startDay', 'endDay')},
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderCode', models.CharField(max_length=20)),
                ('orderDay', models.DateTimeField(auto_now_add=True)),
                ('destinationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersystem.Destination')),
                ('goodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersystem.Goods')),
            ],
            options={
                'unique_together': {('orderCode', 'id')},
            },
        ),
    ]
