# Generated by Django 2.2.5 on 2019-09-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
