# Generated by Django 2.2.5 on 2019-09-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersystem', '0002_orders_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='enterprise',
            new_name='enterprise_id',
        ),
    ]
